<?php $__env->startSection('page_title', 'Service Users | AddMagPro Admin'); ?>
<?php $__env->startSection('mainsection'); ?>
<div class="admin-page"><section class="admin-section"><div class="admin-section-body">
  <div class="mb-4"><h2 class="admin-page-title">Service Users</h2><p class="admin-page-subtitle">Pending service listings and approval actions.</p></div>
  <div class="card admin-card"><div class="card-header admin-card-header"><h4>Service Users</h4></div><div class="card-body admin-card-body p-0"><div class="table-responsive admin-table-wrap"><table class="table admin-table align-middle mb-0">
    <thead><tr><th>#</th><th>User</th><th>Mobile</th><th>PAN</th><th>Address</th><th>Service Type</th><th>Business Image</th><th>Status</th><th>Action</th></tr></thead>
    <tbody><?php $__empty_1 = true; $__currentLoopData = $service_users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e(method_exists($service_users, 'firstItem') ? $service_users->firstItem() + $index : $index + 1); ?></td><td class="fw-semibold text-dark"><?php echo e($user->member_name ?? '-'); ?></td><td><?php echo e($user->member_phone ?? '-'); ?></td><td><?php echo e($user->pan_number ?? '-'); ?></td><td class="admin-table-long"><?php echo e($user->address ?? '-'); ?></td><td><?php echo e($user->profession ?? '-'); ?></td><td><?php if(!empty($user->business_image)): ?><img src="<?php echo e(asset($user->business_image)); ?>" class="admin-thumb" alt="Business image"><?php else: ?> - <?php endif; ?></td><td><span class="status-badge <?php echo e((string)($user->status ?? '') === '1' ? 'badge-approved' : 'badge-rejected'); ?>"><?php echo e((string)($user->status ?? '') === '1' ? 'Approved' : 'Not Approved'); ?></span></td><td><a href="<?php echo e(route('business_listing_status_update', ['id' => $user->service_user_id])); ?>" class="btn btn-theme btn-sm">Update</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="9" class="text-center text-muted py-4">No service users found.</td></tr><?php endif; ?></tbody>
  </table></div></div><div class="card-footer admin-card-footer d-flex justify-content-end"><?php echo e($service_users->links()); ?></div></div>
</div></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.master', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\admagpro\resources\views/admin_pages/users/serviceusers.blade.php ENDPATH**/ ?>